### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by HerbieHSSO** [JonathanMurray/gb-pymulator#1]
this is not really a question however, I wanted to help you, I changed the while True to For ranges (this makes the loops much faster) I got an even better result using PyPy (basically Python but with the optimization of the C language. I got much more interesting results, the number of cycles practically doubled!)

**Comment by JonathanMurray** [comment]
Heya!

>  changed the while True to For ranges (this makes the loops much faster)

Sounds interesting! You mean this one? https://github.com/JonathanMurray/gb-pymulator/blob/master/gb_pymulator/emulator.py#L99 What would it look like after your change?

Regarding PyPy, yeah I should really use it. For some reason I couldn't get it installed correctly on my Macbook along with Pygame. I don't remember the exact issue now, but it surely would have been much less trouble just going with PyPy than implementing all the Cython bindings.

When you say you got twice the cycle rate, do you mean compared to running the emulator in regular Python or compared to running it with Cython?

**Comment by HerbieHSSO** [comment]
1. Yes!

2. I also got this error in PyPy on Windows and I only managed to fix it by installing the "developer" version of Pygame!

3.Regular Python!

**Comment by HerbieHSSO** [comment]
testing the program without using PyPy and changing the While True to the For Range I realized that there is a "bottleneck", switching the while to for you notice that there is a delay in responses similar to "with while", I am investigating this and apparently it is a problem of the python own variable calling system, I will try to call a solution.
My goal is to try to make Python as fast as the C language using external libs or not (if the project is completed possibly we will have an improvement in the amount of emulators made in Python!)
